version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    enviroment:
      VITE_API_URL: "http://localhost:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST:  "localhost"
      DB_PASSWORD: "#Kaua1509"
      DB_DATABASE: "fercorretora"
      DB_NAME: "fercorretora"
      DB_PORT: "5432"
      DB_USERNAME: "kaua"
      SECRET: "Iss0Aqu1N@0EBr1ncad3ir4"
      PORT: 8000
